title: Yoel Suryo
logo: images/profile-icon.png
description: Geodetic Engineering | GIS Surveyor and Spatial Data Analyst | WebGIS Developer Enthusiast | Data & Mapping Enthusiast
show_downloads: false
theme: jekyll-theme-minimal
