logo: images/profile-icon.png
title: Hi! I am Yoel Suryo Putro Darmawan
description: Geodetic Engineering | GIS Surveyor and Spatial Data Analyst | WebGIS Developer Enthusiast | Data & Mapping Enthusiast
location: "Semarang"
show_downloads: false
theme: jekyll-theme-minimal
