title: MY Portofolio
logo: images/profile-icon.png
title: "Yoel Suryo"
title: "I am a man newbie on all of this"
description: Geodetic Engineering | GIS Surveyor and Spatial Data Analyst | WebGIS Developer Enthusiast | Data & Mapping Enthusiast
location: "Semarang"
show_downloads: false
theme: jekyll-theme-minimal
